# Generated by Django 2.1.7 on 2019-04-03 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='LabSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(max_length=3)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApplication.Course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=60)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='labsection',
            name='section_TA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApplication.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_TAs',
            field=models.ManyToManyField(to='WebApplication.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApplication.User'),
        ),
    ]
