# Generated by Django 2.1.7 on 2019-05-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=50)),
                ('course_code', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='LabSection',
            fields=[
                ('lab_number', models.CharField(default='', max_length=5)),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApplication.Course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('role', models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('ADMINISTRATOR', 'Administrator'), ('INSTRUCTOR', 'Instructor'), ('TA', 'TA')], default='1', max_length=13)),
                ('phone', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='labsection',
            name='lab_ta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApplication.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_instructor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApplication.User'),
        ),
    ]
