# Generated by Django 2.1.7 on 2019-04-30 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_instructor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApplication.User'),
        ),
        migrations.AlterField(
            model_name='labsection',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApplication.Course'),
        ),
        migrations.AlterField(
            model_name='labsection',
            name='lab_ta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApplication.User'),
        ),
    ]
