# Generated by Django 2.1.7 on 2019-04-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0002_auto_20190411_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('ADMINISTRATOR', 'Administrator'), ('INSTRUCTOR', 'Instructor'), ('TA', 'Ta')], default='1', max_length=9),
        ),
    ]
