# Generated by Django 2.1.7 on 2019-04-09 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0002_auto_20190406_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_TAs',
        ),
        migrations.RemoveField(
            model_name='labsection',
            name='section_TA',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='course',
            name='course_tas',
            field=models.ManyToManyField(default=None, to='WebApplication.TA'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='instructor_field',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='ta',
            name='ta_field',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='WebApplication.Instructor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='labsection',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='WebApplication.Course'),
        ),
        migrations.AlterField(
            model_name='labsection',
            name='section_number',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
