# Generated by Django 2.1.7 on 2019-04-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0003_auto_20190411_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('ADMINISTRATOR', 'Administrator'), ('INSTRUCTOR', 'Instructor'), ('TA', 'Ta')], default='1', max_length=13),
        ),
    ]
