# Generated by Django 2.1.7 on 2019-04-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0004_auto_20190411_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labsection',
            old_name='section_number',
            new_name='lab_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_tas',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='labsection',
            name='lab_tas',
            field=models.ManyToManyField(default=None, related_name='ta_list', to='WebApplication.User'),
        ),
    ]
